name: Check Style Code

on:
  push:
    branches:
      - new_brench

  pull_request:
    branches:
      - new_brench

jobs:
  checkstyle_progject:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone repo
        uses: actions/checkout@v2

      - name: Set version Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.6'

      - name: Install dependencies
        run:
          pip install flake8

      - name: Run linter
        run:
          flake8
